import { assertPortfolio,calculateImpact,formatInr,orderedPositions,portfolio } from './src/portfolio.js';
assertPortfolio(portfolio);
const storage={get(key,fallback){try{return localStorage.getItem(key)??fallback}catch{return fallback}},set(key,value){try{localStorage.setItem(key,value)}catch{}}};
document.querySelector('#position-list').innerHTML=orderedPositions(portfolio.positions).map(({ticker,name,sector,value,move,thesis})=>`<article class="position"><span class="ticker">${ticker}</span><div><strong>${name}</strong><span>${sector} · ${thesis}</span></div><div><b>${formatInr(value,true)}</b><span class="${move>=0?'positive':'negative'}">${move>=0?'+':'−'}${Math.abs(move)}%</span></div></article>`).join('');
document.querySelector('#portfolio-value').textContent=formatInr(portfolio.value);document.querySelector('#today').textContent=new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
const slider=document.querySelector('#drawdown');function updateScenario(){const marketMove=Number(slider.value);const impact=calculateImpact(portfolio.value,portfolio.equityWeight,marketMove);document.querySelector('#drawdown-output').value=`${marketMove>0?'+':marketMove<0?'−':''}${Math.abs(marketMove)}%`;const result=document.querySelector('#scenario-change');result.textContent=`${impact>0?'+':impact<0?'−':''}${formatInr(Math.abs(impact))}`;result.className=impact>=0?'positive':'negative';document.querySelector('#scenario-copy').textContent=marketMove===0?'No modeled market move':`Equity sleeve at a ${Math.abs(marketMove)}% market ${marketMove<0?'drawdown':'advance'}`;}slider.addEventListener('input',updateScenario);updateScenario();
const theme=storage.get('mprofit.theme','light');document.body.dataset.theme=theme;const themeButton=document.querySelector('#theme-toggle');themeButton.textContent=theme==='dark'?'Use light':'Use dark';themeButton.addEventListener('click',()=>{const next=document.body.dataset.theme==='dark'?'light':'dark';document.body.dataset.theme=next;storage.set('mprofit.theme',next);themeButton.textContent=next==='dark'?'Use light':'Use dark';});
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.view===button.dataset.view));document.querySelector(`#${button.dataset.view}`)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}));
const note=document.querySelector('#decision-text');note.value=storage.get('mprofit.note',note.value);document.querySelector('#save-note').addEventListener('click',()=>{storage.set('mprofit.note',note.value.trim());document.querySelector('#saved-message').textContent='Decision saved on this device.';});
